import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {spawnSync} from 'node:child_process';
const executable = process.env.LUAU_EXECUTABLE || '.local/tools/luau-0.737/luau.exe';
await mkdir('.local', {recursive:true});
const source = await readFile('studio/Rig.lua','utf8');
const tests = await readFile('tests/accessories.luau','utf8');
const column = await readFile('studio/EnergyColumn.lua', 'utf8');
const columnTests = await readFile('tests/energy-column.luau', 'utf8');
await writeFile('.local/studio-tests.luau', `local game = {GetService=function() return {} end}\nlocal Rig = (function()\n${source}\nend)()\n${tests}\nlocal EnergyColumn = (function()\n${column}\nend)()\n${columnTests}`);
const result = spawnSync(executable, ['.local/studio-tests.luau'], {encoding:'utf8'});
if (result.error) throw result.error;
process.stdout.write(result.stdout);
process.stderr.write(result.stderr);
process.exitCode = result.status ?? 1;
