import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {spawnSync} from 'node:child_process';
const executable = process.env.LUAU_EXECUTABLE || '.local/tools/luau-0.737/luau.exe';
await mkdir('.local', {recursive:true});
const source = await readFile('studio/Rig.lua','utf8');
const tests = await readFile('tests/accessories.luau','utf8');
const column = await readFile('studio/EnergyColumn.lua', 'utf8');
const columnTests = await readFile('tests/energy-column.luau', 'utf8');
await writeFile('.local/studio-tests.luau', `local game = {GetService=function() return {} end}\nlocal Rig = (function()\n${source}\nend)()\n${tests}\nlocal EnergyColumn = (function()\n${column}\nend)()\n${columnTests}`);
const result = spawnSync(executable, ['.local/studio-tests.luau'], {encoding:'utf8'});
if (result.error) throw result.error;
process.stdout.write(result.stdout);
process.stderr.write(result.stderr);
process.exitCode = result.status ?? 1;
const plugin = await readFile('studio/Plugin.lua', 'utf8');
const pluginTests = (await readFile('tests/plugin-library.luau', 'utf8')).replace('-- INSERT_PLUGIN_HERE', plugin);
await writeFile('.local/plugin-library-tests.luau', pluginTests);
const panelResult = spawnSync(executable, ['.local/plugin-library-tests.luau'], { encoding: 'utf8' });
if (panelResult.error) throw panelResult.error;
process.stdout.write(panelResult.stdout);
process.stderr.write(panelResult.stderr);
if (panelResult.status !== 0) process.exitCode = panelResult.status ?? 1;
let inspectionTests = await readFile('tests/motion-inspection.luau', 'utf8');
for (const [marker, file] of [['AUTHORING', 'Authoring'], ['PREVIEW', 'Preview'], ['INSPECTION', 'MotionInspection']]) {
  const module = await readFile(`studio/${file}.lua`, 'utf8');
  inspectionTests = inspectionTests.replace(`-- INSERT_${marker}_HERE`, () => module);
}
await writeFile('.local/motion-inspection-tests.luau', inspectionTests);
const inspectionResult = spawnSync(executable, ['.local/motion-inspection-tests.luau'], { encoding: 'utf8' });
if (inspectionResult.error) throw inspectionResult.error;
process.stdout.write(inspectionResult.stdout);
process.stderr.write(inspectionResult.stderr);
if (inspectionResult.status !== 0) process.exitCode = inspectionResult.status ?? 1;
